// The default cluster, mirroring examples/ in the repo: three nodes and the
// a/b/c workloads behind services. No policies — traffic defaults to allow
// until someone applies one. Calls are generated by the simulator itself:
// every Ready instance dials a random service other than its own.

import type { KliteObject, Service, Workload } from '@/api/types'

function node(name: string): KliteObject {
  return {
    apiVersion: 'klite/v1',
    kind: 'Node',
    metadata: { name, labels: { zone: 'local' } },
    spec: { maxInstances: 32 },
  }
}

function service(name: string): Service {
  return {
    apiVersion: 'klite/v1',
    kind: 'Service',
    metadata: { name },
    spec: { selector: { app: name }, port: 8080, targetPort: 80 },
  }
}

function whoami(name: string, replicas: number): Workload {
  return {
    apiVersion: 'klite/v1',
    kind: 'Workload',
    metadata: { name, labels: { app: name } },
    spec: {
      replicas,
      template: {
        labels: { app: name },
        containers: [
          {
            name: 'web',
            image: 'traefik/whoami:v1.10',
            env: [{ name: 'WHOAMI_NAME', value: name }],
            ports: [{ containerPort: 80 }],
            readinessProbe: { tcpPort: 80 },
          },
        ],
      },
    },
  }
}

const clientWorkload: Workload = {
  apiVersion: 'klite/v1',
  kind: 'Workload',
  metadata: { name: 'a', labels: { app: 'a' } },
  spec: {
    replicas: 1,
    template: {
      labels: { app: 'a' },
      containers: [
        {
          name: 'client',
          image: 'alpine:3.20',
          command: ['/bin/sh', '-c'],
          args: [
            'while true; do wget -qO- -T 2 http://b:8080; wget -qO- -T 2 http://c:8080; sleep 1; done',
          ],
        },
      ],
    },
  },
}

export function seedObjects(): KliteObject[] {
  return [
    node('node-1'),
    node('node-2'),
    node('node-3'),
    clientWorkload,
    service('a'),
    whoami('b', 2),
    service('b'),
    whoami('c', 2),
    service('c'),
  ]
}
